quarkus:
  datasource:
    db-kind: sqlite
    jdbc:
      url: jdbc:sqlite:./data/data.db

  hibernate-orm:
    schema-management:
      strategy: update
    log:
      format-sql: true

  rest-client:
    prometheus:
      url: ${PROMETHEUS_URL:http://localhost:9090}
      connect-timeout: 2000
      read-timeout: 5000

  scheduler:
    enabled: true

  http:
    cors:
      ~: true
      origins: ${CORS_ORIGINS:http://localhost:3000}

broder:
  scheduler:
    interval: 20s
  webhook:
    timeout-seconds: 5
