server.port=3000
spring.application.name=api-prometheus

# Actuator configuration
# Moveprometheus endpoint from /actuator/prometheus to /metrics
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=prometheus
management.endpoints.web.path-mapping.prometheus=metrics

# Enable standard metrics
management.metrics.tags.application=${spring.application.name}
management.metrics.export.prometheus.enabled=true